### ISSUE TITLE
Incorrect links for projects in dashboard projects view

### ISSUE THREAD

**Issue by arihanv** [RubricLab/maige#128]
https://github.com/RubricLab/maige/assets/63890951/94692475-ef94-491b-bcbc-c0a9d050cab6

**Comment by arihanv** [comment]
maige label this

**Comment by tedspare** [comment]
Maige label this

**Comment by tedspare** [comment]
maige could you dispatch an eng to fix this? TLDR: the project card repo link uses username, but should use team slug I think or possibly organization slug

**Comment by tedspare** [comment]
maige dispatch an engineer to fix this

**Comment by tedspare** [comment]
maige could you please dispatch an engineer to fix this?

**Comment by sarimrmalik** [comment]
Closing this issue since this does not exist in prod, it only existed for our Rubric workspace because it was an old product which was missing an organization ID. Fixed.
