### ISSUE TITLE
maige goes crazy

### ISSUE THREAD

**Issue by felixhaeberle** [RubricLab/maige#129]
### Screenshot

<img width="911" alt="Bildschirmfoto 2024-02-16 um 09 13 54" src="https://github.com/RubricLab/maige/assets/34959078/622b954a-8dd5-4856-8827-77481c5ee871">

### Link

https://github.com/opral/monorepo/issues/2237

### Description

This is not what it is supposed to do, can you fix it? Btw it's the first time it goes that crazy.

**Comment by tedspare** [comment]
On it. Thanks for flagging this, Felix.

**Comment by sarimrmalik** [comment]
Should be fixed by #131, feel free to reopen if the issue persists. Thanks for trying Maige as we make it better :)
