### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by DexterStorey** [RubricLab/maige#89]
The build errors in main with the following message:

Failed to compile.

./node_modules/lodash/_SetCache.js
Module not found: Can't resolve './_MapCache'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/lodash/_baseUniq.js
./node_modules/lodash/uniqBy.js
./node_modules/recharts/es6/util/payload/getUniqPayload.js
./node_modules/recharts/es6/component/Legend.js
__barrel_optimize__?names=CartesianGrid,Dot,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis!=!./node_modules/recharts/es6/index.js
./node_modules/@tremor/react/dist/components/chart-elements/LineChart/LineChart.js
__barrel_optimize__?names=LineChart!=!./node_modules/@tremor/react/dist/index.js
./lib/components/dashboard/Usage/Chart.tsx

...

**Comment by DexterStorey** [comment]
maige assign this to me plz

**Comment by DexterStorey** [comment]
maige beta assign this to me plz

**Comment by DexterStorey** [comment]
maige beta can you provide context about how to fix this?

**Comment by DexterStorey** [comment]
maige beta open a new issue: Maige doesn't know we're using bun when answering questions

**Comment by DexterStorey** [comment]
maige beta open a new issue: Maige successfully opens new issues but doesn't provide feedback to say that the issue has been opened, and doesn't reference that issue in the thread.

Attach these screenshot to the new issue:

<img width="668" alt="Screenshot 2024-01-19 at 9 46 29 PM" src="https://github.com/RubricLab/maige/assets/36115192/d9876225-6d63-4bf2-b740-ff8fae52691c">
<img width="773" alt="Screenshot 2024-01-19 at 9 45 53 PM" src="https://github.com/RubricLab/maige/assets/36115192/cb1559a3-7af8-4ecb-a1e2-eb9b76feb79b">

**Comment by DexterStorey** [comment]
barz dog. S tier gaslighting u the goat no cap

**Comment by tedspare** [comment]
Maige label this

**Comment by tedspare** [comment]
Maige label this
