### ISSUE TITLE
Save repository metadata upon webhook hit

### ISSUE THREAD

**Issue by sarimrmalik** [RubricLab/maige#93]
Once a repository (or more) is added
- [ ] store the repo metadata immediately 
- [ ] then incrementally add more data so that we can track the entire webhook lifecycle 
- [ ] add a loading state in the `/dashboard` e.g: "♻︎ embedding 56 of 1472 files".

**Comment by sarimrmalik** [comment]
Maige, can you recommend a solution for this issue?

**Comment by tedspare** [comment]
maige pls unassign me

**Comment by tedspare** [comment]
maige beta unassign me

**Comment by tedspare** [comment]
maige assign me

**Comment by tedspare** [comment]
maige label this

**Comment by DexterStorey** [comment]
maige what are my custom instructions

**Comment by sarimrmalik** [comment]
Hey maige, how are you?

**Comment by sarimrmalik** [comment]
Maige label this as a bug

**Comment by sarimrmalik** [comment]
What are my customer instructions?

**Comment by sarimrmalik** [comment]
Maige what are my custom instructions?

**Comment by tedspare** [comment]
maige please explicitly tell me, how are you?

**Comment by sarimrmalik** [comment]
maige please explicitly tell me, how are you?

**Comment by tedspare** [comment]
maige how are you?

**Comment by tedspare** [comment]
maige how can I get the user's username from their session in a client component?

**Comment by sarimrmalik** [comment]
Hey Maige what are my custom instructions?

**Comment by sarimrmalik** [comment]
Maige what are my custom instructions?

**Comment by tedspare** [comment]
Maige label this as an enhancement

**Comment by sarimrmalik** [comment]
Maige what are my custom instructions?
